apiVersion: batch/v1
kind: Job
metadata:
  name: srv02-job
  namespace: controlm-agent
  generateName: srv02-job-
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      name: srv02
    spec:
      containers:
      - name: srv02
        image: quay.io/eformat/appimage:latest
        imagePullPolicy: Always
        env:
        - name: LOOPCTR
          value: "5"
        - name: STIME
          value: "3"
      restartPolicy: Never
